services:
  web:
    build: .
    container_name: my_app_node
    restart: always
    volumes:
      - .:/usr/app/
    ports:
      - "8081:8081"
    command:
      "npm run dev"
    env_file:
      - ./.env
