services:
  web:
    build: .
    container_name: my_app_node
    restart: always
    volumes:
      - .:/app/
    ports:
      - "8081:8081"
    command:
      "npm run start"
    env_file:
      - ./.env
# el npm run start era antes (backend) un npm run dev