const options = [
  { value: 'agricola', label: 'Agrícola' },
  { value: 'alimento', label: 'Alimento' },
  { value: 'animales', label: 'Animales' },
  { value: 'arte', label: 'Arte' },
  { value: 'ayuda social', label: 'Ayuda Social' },
  { value: 'brecha tecnologica', label: 'Brecha Tecnológica' },
  { value: 'calentamiento global', label: 'Calentamiento Global' },
  { value: 'campamentos', label: 'Campamentos' },
  { value: 'conservacion', label: 'Conservación' },
  { value: 'contaminacion', label: 'Contaminación' },
  { value: 'deporte', label: 'Deporte' },
  { value: 'desigualdad', label: 'Desigualdad' },
  { value: 'discapacidad', label: 'Discapacidad' },
  { value: 'discapacidad intelectual', label: 'Discapacidad Intelectual' },
  { value: 'discapacidad motora', label: 'Discapacidad Motora' },
  { value: 'educacion', label: 'Educación' },
  { value: 'educación básica', label: 'Educación Básica' },
  { value: 'educacion media', label: 'Educación Media' },
  { value: 'educacion superior', label: 'Educación Superior' },
  { value: 'equidad', label: 'Equidad' },
  { value: 'energia', label: 'Energía' },
  { value: 'energias renovables', label: 'Energías Renovables' },
  { value: 'entretencion', label: 'Entretención' },
  { value: 'ganadero', label: 'Ganadero' },
  { value: 'guerra', label: 'Guerra' },
  { value: 'igualdad', label: 'Igualdad' },
  { value: 'incendios', label: 'Incendios' },
  { value: 'incendios forestales', label: 'Incendios Forestales' },
  { value: 'infancia', label: 'Infancia' },
  { value: 'medioambiente', label: 'Medioambiente' },
  { value: 'niñez', label: 'Niñez' },
  { value: 'pensiones', label: 'Pensiones' },
  { value: 'personas mayores', label: 'Personas Mayores' },
  { value: 'pobreza', label: 'Pobreza' },
  { value: 'politica', label: 'Política' },
  { value: 'preservacion', label: 'Preservación' },
  { value: 'recursos naturales', label: 'Recursos Naturales' },
  { value: 'recursos renovables', label: 'Recursos Renovables' },
  { value: 'rehabilitacion', label: 'Rehabilitación' },
  { value: 'reinserción social', label: 'Reinserción Social' },
  { value: 'salud', label: 'Salud' },
  { value: 'sectores vulnerables', label: 'Sectores Vulnerables' },
  { value: 'sociedad', label: 'Sociedad' },
  { value: 'telecomunicaciones', label: 'Telecomunicaciones' },
  { value: 'textiles', label: 'Textiles' },
  { value: 'uso de agua', label: 'Uso de Agua' },
  { value: 'veganismo', label: 'Veganismo' },
  { value: 'vegetarianismo', label: 'Vegetarianismo' },
  { value: 'vivienda', label: 'Vivienda' },
];

export default options;
